service_app/urls.py
# from django.contrib import admin
from django.urls import path
from service_app import views
from django.conf import settings
from django.conf.urls.static import static

import service_app
app_name = 'service_app' 
urlpatterns = [
    path("", views.index, name="home"),
    path("<int:myid>",views.showservice,name="showservice"),
    path("about", views.about, name="about"),
    path("contact", views.contact, name="contact"),
    path("search",views.SearchView.as_view(),name="search"),
    path("services", views.services, name="services"),
    path("<slug:category_slug>",views.services,name="service_category"),
    path("showservice/<int:myid>",views.showservice,name="showservice"),
    path("addtocart/<int:ser_id>",views.AddToCartView.as_view(), name='services'),
    path('service_app/mycart/', views.MyCartView.as_view(), name='mycart'),
    path('managecart/<int:cs_id>/', views.ManageCartView.as_view(), name='managecart'),
    path('emptycart/', views.EmptyCartView.as_view(), name='emptycart'),
     path('checkout/', views.CheckoutView.as_view(), name='checkout'),
    path('service_app/register/', views.CustomerRegistrationView.as_view(), name='customerregistration'),
     path('service_app/login/', views.CustomerLoginView.as_view(), name='customerlogin'),
     path('service_app/logout/', views.CustomerLogoutView.as_view(), name='customerlogout'),
      path('service_app/profile/', views.CustomerProfileView.as_view(), name='customerprofile'),
    

]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

twowheeler_service_system/urls.py
from django.contrib import admin
from django.urls import path,include


admin.site.site_header = "Service booking app admin Panel"
admin.site.site_title = "admin Panel"
admin.site.index_title = "Service booking app"

urlpatterns = [
    # Url dispatching
    path("", include("service_app.urls")),
    path('admin/', admin.site.urls),
]

service_app/models.py
import uuid
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.db.models.fields import DurationField
from .manager import UserManager
from django.urls import reverse

# from django.core.validators import User

# from django.utils import timezone

# Create your models here.
class Vehicle(models.Model):
    id = models.UUIDField(primary_key= True,default=uuid.uuid4, editable=False)
    name = models.CharField(("Name of Vehicle"), blank=True, max_length=255)
    type = models.CharField(("Type of Vehicle"), blank=True, max_length=255)
    fuel_type = models.CharField(blank=True, max_length=255)
    chassis_no =models.CharField(blank=True, max_length=255)
    is_active = models.BooleanField(default=False)
    image = models.ImageField(upload_to = "vehicle/images",default = "")

    def __str__(self):
        return self.name

class Model (models.Model):
    id = models.UUIDField(primary_key=True,default=uuid.uuid4,editable=False)
    # Vehicle = models.ForeignKey(Vehicle, on_delete=models.CASCADE)
    name = models.CharField(blank=True,max_length=255)
    is_active = models.BooleanField(default=False)
class Categorie(models.Model):
    name = models.CharField(("Name of Category"), blank=True, max_length=255)
    slug = models.SlugField(unique=True )
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
    def get_absolute_url(self):
        return reverse('service_app:service_category', args=[self.slug])
    # def get_all_services_by_id(categorie_id):
    #     if categorie_id:
    #         return Service.objects.filter(categorie =categorie_id)
    #     else:
    #         return Service.objects.all()



class Service(models.Model):
    name = models.CharField(("Name of Service"), blank=True, max_length=255) 
    Duration = models.CharField(blank=True,max_length=30)
    Warranty = models.CharField(blank=True,max_length=30)
    what_included = models.CharField( blank=True, max_length=1900) 
    image = models.ImageField(upload_to = "service/images",default = "")
    price =models.IntegerField(default=0)
    Categorie =models.ForeignKey(Categorie,on_delete=models.CASCADE,default=1)
    is_active = models.BooleanField(default=False)

    def __str__(self):
        return self.name
class Contact(models.Model):
    msg_id = models.AutoField(primary_key=True)
    name =models.CharField(max_length=50)
    email =models.CharField(max_length=70,default="")
    phone =models.CharField(max_length=70,default="")
    desc =models.CharField(max_length=500,default="")
    def __str__(self):
            return self.name






class User(AbstractUser):
    # id= models.UUIDField(primary_key= True,default=uuid.uuid4, editable=False) 
    username = None
    email = models.EmailField(unique=True)
    is_verified =models.BooleanField(default=False)
    last_login_time = models.DateTimeField(null=True,blank=True)
    last_logout_time = models.DateTimeField(null=True,blank=True)

    objects = UserManager()


    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []
class Customer(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)
    full_name = models.CharField(max_length=200)
    address = models.CharField(max_length=200, null=True, blank=True)
    joined_on = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return self.full_name
class Cart(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.SET_NULL, null=True, blank=True)
    total = models.PositiveIntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return "Cart: " + str(self.id)

class CartService(models.Model):
    cart = models.ForeignKey(Cart, on_delete=models.CASCADE)
    service = models.ForeignKey(Service, on_delete=models.CASCADE)
    rate = models.PositiveIntegerField()
    quantity = models.PositiveIntegerField()
    subtotal = models.PositiveIntegerField()

    def __str__(self):
        return "Cart: " + str(self.cart.id) + "CartService: " + str(self.id)
ORDER_STATUS = (
    ("Order Received", "Order Received"),
    ("Order Processing", "Order Processing"),
    ("On The Way", "On The Way"),
    ("Order Completed", "Order Completed"),
    ("Order Canceled", "Order Canceled")
)
# METHOD = (
#     ("Cash On Delivery ", "Cash On Delivery "),
# )
# SERVICE_MODE=(
#     ("Self Pick up and Drop","Self Pick up and Drop"),
#     (" Pick up and Drop by Mechanic","Pick up and Drop by Mechanic"),

# )


class Order(models.Model):
    cart = models.OneToOneField(Cart, on_delete=models.CASCADE)
    ordered_by = models.CharField(max_length=200)
    address = models.CharField(max_length=200 ,default="")
    date =models.DateField(null=True,blank=True)
    Time =models.TimeField(null=True,blank=True)
    mobile = models.CharField(max_length=200)
    email = models.EmailField(null=True, blank=True)
    subtotal = models.PositiveIntegerField()
    discount = models.PositiveIntegerField()
    total = models.PositiveIntegerField()
    order_status = models.CharField(max_length=50, choices=ORDER_STATUS)
    created_at = models.DateTimeField(auto_now_add=True)
    # type =models.CharField(max_length=50,choices=SERVICE_MODE ,default="" )


    def __str__(self):
        return "Order: " + str(self.id)







    



    










# Create your models here.

templates/about.html
{% extends 'base.html' %}

{% block title %}About{% endblock title %}
<head>
      <style>
    .au-head {
      color: #fff;
      font-size: 42px !important;
    }

    p.au-sign {
      font-size: 15px
    }

    .au-sign span {
      font-size: 14px
    }

    .grey-bg::before {
      width: 96.5%;
    }

    .grey-bgfull::before {
      width: 100% !important;
    }

    .emp-pos {
      color: #000 !important;
      margin-bottom: 5px;
    }

    .emp-blk {
      margin: 50px 10px;
    }

    .emp-para {
      padding: 6px 0;
      background: #fff;
      margin-top: 20px;
      position: relative;
    }

    .emp-para::before {
      position: absolute;
      content: '';
      width: 0;
      height: 0;
      border-left: 15px solid transparent;
      border-right: 15px solid transparent;
      border-bottom: 15px solid white;
      left: 0;
      right: 0;
      top: 0;
      margin: 0 auto;
      margin-top: -15px;
    }
    .level-menu nav.page-nav ul {
      display:flex !important;
    }
  </style>
  </head>

{% block body %}
<body>

  <!--================================
HEADER
==================================-->

  <div id="headerContent"></div>

  <!--================================
PAGE WRAP
==================================-->

  <div class="page-wrap">

    <!--================================
CONTENT
==================================-->
    <div class="parallax-container about-us">
      <div class="container-fluid parallax-text">
        <div class="row">
          <div class="col-md-12 text-center">
    

    <!-- nav bar Start-->
      <div class="level-menu level-menu-environment" id="pageLevelMenu"></div>
    <!-- nav bar End -->

    <div class="container-fluid">
      <div class="row add-mrgtop wow bounceInUp">
        <div class="col-md-3">
          <div class="md-img text-center"> <img class=" lazy" src="/media/gettyimages-188052258-612x612.jpg" alt=".."style=" width: 350px;
  height: 500px;">
            <p style="font-size:15px;margin-top:10px;">
              <span style="font-size: 14px; ">
            </p>
          </div>
        </div>
        <div class="col-md-9 grey-bg">
          <div class="col-md-12">
            <article class="content-para">
              <h1 class="article-head">Quality You Can Trust</h1>
              <p>At Rogers, we uphold the philosophy of continuous improvement (Kaizen) because we believe that there is
                always scope to do better. It is this very philosophy that drives us towards quality, making it a way of
                life at Rogers. </p>
              <p>The tradition at Rogers has always been to provide premium quality cars backed with reliable services
                to our customers. We ensure that the quality meets the international standards while keeping in mind the
                local sensitivities. </p>
              <p>Our firm belief in putting customers first has constantly enabled us to respond effectively to your
                needs, whether in terms of quality, service or the driving experience. </p>
              <p>Rogers's renowned reputation of Quality Durability and Reliability (QDR) has led our steady growth in
                the Indian automotive market. We are proud to declare that over 1 million Indians are part of the ever
                growing Rogers family. </p>
              <p>We also strive towards developing a more sustainable future and being pioneers in the Hybrid Technology
                is our first step towards this movement. Through initiatives focused on education, community development
                and the environment, we aim to create a company that works in harmony with nature and society. </p>
              <p>I would like to thank all our partners who have been instrumental in our growth. We look forward to
                strengthening our relationship with you and welcome you to be a part of the Rogers family. </p>
              <strong>

              </strong>
            </article>
          </div>
        </div>
      </div>
  
       
    <div class="full-width add-mrgtop grey-bg grey-bgfull ">
      <div class="row">
        <div class="col-md-12 col-lg-12">
          <div class="container">
            <div class="row">
              <!--<div class="col-md-4 text-center">
                <div class="emp-blk wow zoomIn">
                  <div class="emp-img"> <img class=" lazy" src="/images/toyota-in-india/about/img1.png"
                      alt="Shekar Viswanathan"> </div>
                  <div class="emp-para">
                    <p class="emp-pos">Vice Chairman & <br>
                      Whole-time Director</p>
                    <p> <strong>Mr. Shekar Viswanathan </strong> </p>
                  </div>
                </div>
              </div>-->



            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
  <div class="container-fluid">
    <div class="row add-mrgtop wow bounceInUp">
      <div class="col-md-4">
        <div class="md-img text-center"> <img class=" lazy" src="https://static2.toyotabharat.com/images/toyota-in-india/about/emp1.jpg" alt="Our Most Valuable Asset - Our Employees"> </div>
      </div>
      <div class="col-md-8">
        <div class="col-md-12">
          <article class="content-para">
            <h1 class="article-head">Our Most Valuable Asset - Our Employees</h1>
            <p>At Toyota, the philosophy of Mutual Trust and Respect is at the core. Our employees are vital and
              inevitably the most valuable asset. We aim to provide a stable employment and world-class working
              conditions balanced with the progress of the company.</p>
            <p>The company's fundamental DNA- the Toyota Way enables us to transcend language and nationality. The two
              supporting pillars are: </p>
            <p><strong>Constant Improvement:</strong> We put forth only the best ideas and efforts.</p>
            <p> <strong>People, a priority:</strong> We firmly believe in individual efforts and good team work. From
              the perspective of Human Resource Management, we strive towards: </p>
            <p>Ensuring a work environment where trust is foremost<br>
              Generating a mechanism for continuous improvement<br>
              Building teamwork for optimisation of the entire company<br>
              A committed human resources development</p>
          </article>
        </div>
      </div>
    </div>
    <div class="row add-mrgtop wow bounceInUp">
      <div class="col-md-4">
        <div class="md-img text-center"> <img class=" lazy" src="https://static2.toyotabharat.com/images/toyota-in-india/about/emp2.jpg" alt="Empowering Employees"> </div>
      </div>
      <div class="col-md-8">
        <div class="col-md-12">
          <article class="content-para">
            <h1 class="article-head">Empowering Employees</h1>
            <p>Employees are the main source of inspiration and strength for a company. We, at Toyota, strive to
              reflect 'Continuous Improvement' and 'Respect for People' in all our activities. Employee suggestions
              are taken very seriously and implemented to improve the working environment.
            </p>
            <p>Training programs are a regular feature in Toyota plants across Japan, Taiwan and Indonesia. Quality
              Circles ensure teamwork, innovation and productivity. TKM's concept of 'Information Time' or I-Time
              facilitates direct communication between team members and leaders.
            </p>
            <p>A fully-equipped canteen, lockers, healthcare centres, round-the-clock doctors & commuting facilities
              are just some of the ways the company ensures that employees get the best of opportunities to grow and
              excel.
            </p>
          </article>
        </div>
      </div>
    </div>
  </div>
  <!--================================
FOOTER
==================================-->

  <div id="snav" class="en"></div>
  <footer class="footer add-mrgtop" id="footerContent"> </footer>

  <!--================================
FOOTER END
==================================-->
  
  <script src="https://static2.toyotabharat.com/js/jquery-3.2.1.min.js"></script>
  <script src="https://static2.toyotabharat.com/js/bootstrap.min.js"></script>
  <script src="https://static2.toyotabharat.com/js/common.js"></script>
  <script src="https://static2.toyotabharat.com/js/jquery.lazy.min.js"></script>
  <script src="https://static2.toyotabharat.com/js/wow.min.js"></script>
  <script>

    $(window).scroll(function () {
      "use strict";
      var windowWidth = $(window).width();
      if (windowWidth >= 480) {
        var wScroll = $(this).scrollTop();
        $('.parallax-container .parallax-img').css({
          'transform': 'translate(0px,' + wScroll / 10 + '%)'
        });
      }
    });
    $("#pageLevelMenu").load("./page-menu.html")
    $(document).ready(function (e) {
      $('.lazy').Lazy();
      bk_send('site|main_site, Category|About');
      // ANIMATE CSS JS START
      wow = new WOW(
        {
          animateClass: 'animated',
          offset: 50
        }
      );
      wow.init();
    });

  </script>
</body>
  
{% endblock body %}

templates/addtocart.html
{% extends 'base.html' %}

{% block title %}Cart Page{% endblock %}

{% block  body %}
<h1>Your Product Successfully Added!!!!</h1>
{% endblock %}

templates/checkout.html
{% extends 'base.html' %}
 {% block title %}CheckOut{% endblock title %}
 {% block body %}
 <div class="container mt-3">
    <div class="row">
        <div class="col-md-6">
            <h3>Item in the cart</h3>
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Service</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                    </tr>
                </thead>
                <tbody>
                    {% for cs in cart.cartservice_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cs.service.name}}</td>
                        <td>₹{{cs.rate}}</td>
                        <td>{{cs.quantity}}</td>
                        <td>₹{{cs.subtotal}}</td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan='4' class="text-right">Total</th>
                        <th>₹{{cart.total}}</th>
                    </tr>
                </tbody>
            </table>
            <a class="btn btn-info btn-block" href="{% url 'service_app:services' %}"> Continue Shopping</a>
            <a class="btn btn-secondary btn-block" href="{% url 'service_app:mycart' %}">Update Cart</a>
        </div>
        
        <div class="col-md-6">
        <div class="form-group">
            <h3 class="">Checkout Form</h3>

            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-success">Place Order</button>
            </form>
        </div>
        </div>

    </div>
</div>
<style>
    form{
        background-color: rgb(245, 245, 245);
        font-family: Sofia;
        font-style: initial;
    }
</style>
 
 
 {% endblock body %}

templates/checkvehicle.html
{% extends 'base.html' %}

{% block title %}checkvehicle{% endblock title %}

{% block body %}
 {% comment %} <form  action="{% url 'checkvehicle' %}" method="post">
        {% csrf_token %}
        <div class="form-inline">
            <label>chassis number</label>
            <input type="text" id="chassis_no" name="chassis_no" class="form-control"/>
        </div>
        <br />
        <div class="col-md-4"></div>
        <div class="col-md-4 form-group">
             <input type="submit" class="btn btn-primary form-control" name="" value="Submit">
        </div>
   </form>  {% endcomment %}
    {% comment %} {% include 'messages.html' %} {% endcomment %}
    <form  action="{% url 'checkvehicle' %}" method="post">
        {% csrf_token %}
   <section class="vh-100" style="background-color: #508bfc;">
  <div class="container py-5 h-100">
    <div class="row d-flex justify-content-center align-items-center h-100">
      <div class="col-12 col-md-8 col-lg-6 col-xl-5">
        <div class="card shadow-2-strong" style="border-radius: 1rem;">
          <div class="card-body p-5 text-center">

           

            <div class="form-outline mb-4">
              <input type="text" id="chassis_no"name="chassis_no" class="form-control" />
              <label class="form-label" for="typeEmailX">Enter Chassis number </label>
            </div>


           

            <button class="btn btn-primary btn-lg btn-block" type="submit">Verify</button>

            <hr class="my-4">


          </div>
        </div>
      </div>
    </div>
  </div>
</section>
      


           
{% endblock body %}

templates/contact.html
{% extends 'base.html' %}

{% block title %}Contact{% endblock title %}

{% block body %}
<div class="container my-3">
<h3> Contact Us</h3>
<form action="/contact" method="post">{% csrf_token %}
  <div class="form-group">
    <label for="name">Name</label>
    <input type="text" class="form-control" id="name"name="name" placeholder="Enter your Name">
  </div>
  <div class="form-group">
    <label for="name">Email</label>
    <input type="email" class="form-control" id="email"name="email" placeholder="Enter your EmailID">
  </div>
  <div class="form-group">
    <label for="name">Phone</label>
    <input type="tel" class="form-control" id="phone"name="phone" placeholder="Enter your Phone Number">
  </div>
    <div class="form-group">
        <label for="desc">Write Us your Query</label>
        <textarea class="form-control" id="desc"name="desc" rows="3"></textarea>
  </div>
  <button type="submit" class="btn btn-primary submit">Submit</button>
 
</form>
</div>


{% endblock body %}

templates/customerprofile.html
{% extends 'base.html' %}

{% block title %}Profile{% endblock %}

{% block body %}
<div class="container">
    <div class="row">
        <div class="col-md-5">
            <h3>User information</h3><hr>
            <p><span class="font-weight-bold">Name: </span>{{customer.full_name}}</p>
           
            <p><span class="font-weight-bold">Email: </span>{{customer.user.email}}</p>
        {% comment %} <p><span class="font-weight-bold">Mobile: </span>{{customer.mobile}}</p> {% endcomment %}
            <p><span class="font-weight-bold">Address: </span>{{customer.address}}</p>
            <p><span class="font-weight-bold">joined_on: </span>{{customer.joined_on}}</p>
        </div>
       
    </div>
</div>
{% endblock %}

templates/customerregistration.html
{% extends 'base.html' %}

{% block title %}Registration{% endblock %}

{% block body %}
<style>
    .errorlist{
        color: red;
    }
</style>
<div class="container">
    <div class="row">
        <div class="col-md-6 mx-auto">
            <h3>Customer Registration Form</h3><hr>
            <form action="" method="POST">
                {% csrf_token %}
                {{form.as_p}}
                <button class="btn btn-primary">Register</button>
                {% comment %} <p>I have already an account <a href="{% url 'Core:customerlogin' %}">Login</a></p> {% endcomment %}
            </form>
        </div>

    </div>
</div>

{% endblock %}

templates/messages.html
  {% for message in messages %}
    <div class="alert alert-warning alert-dismissible fade show" role="alert">
  <strong>Holy guacamole!</strong> You should check in on some of those fields below.
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">&times;</span>
  </button>
</div>
 {% endfor %}

templates/mycart.html
{% extends 'base.html' %}

{% block title %}MyCart Page{% endblock %}

{% block body %}
<div class="container">
    <div class="col-md-12">
        <div class="col-md-8">
            <h4 class="mt-3" style="color: darkblue;">Items in my Cart</h4>
        </div>
    </div>

    <div class="row">
        <div class="col-md-8">
            <table class="table">
                <thead>
                    <tr>
                        <th>No</th>
                        <th>Service</th>
                        <th>Rate</th>
                        <th>Quantity</th>
                        <th>Subtotal</th>
                        <th>Action</th>
                      </tr>
                </thead>
                <tbody>
                    {% for cs in cart.cartservice_set.all %}
                    <tr>
                        <td>{{forloop.counter}}</td>
                        <td>{{cs.service.name}}</td>
                        <td>₹{{cs.rate}}</td>
                        <td>{{cs.quantity}}</td>
                        <td>₹{{cs.subtotal}}</td>
                        <td>
                             <a href="{% url 'service_app:managecart' cs.id %}?action=inc" class="btn btn-primary"> + </a>
                            <a href="{% url 'service_app:managecart' cs.id %}?action=dcr" class="btn btn-info"> - </a>
                            <a href="{% url 'service_app:managecart' cs.id %}?action=rmv" class="btn btn-warning"> ×</a> 
                        </td>
                    </tr>
                    {% endfor %}
                    <tr>
                        <th colspan='4' class="text-right">Total</th>
                        <th>₹{{cart.total}}</th>
                        {% if cart.cartservice_set.all %}
                         <th><a href="{% url 'service_app:emptycart' %}">Empty</a></th> 
                        {% endif %}
                    </tr>
                </tbody>
            </table>
        </div> 

        { <div class="container col-md-4">
            <div class="mb-2">
                <a class="btn btn-outline-info btn-block" href="{% url 'service_app:services' %}"> Continue Shopping</a>
            </div>
            <div class="mb-2">
                {% if cart.cartservice_set.all %}
                <a class="btn btn-outline-success btn-block" href="{% url 'service_app:checkout' %}">CheckOut</a>
                {% endif %}
            </div>
        </div> 
    </div>
</div>
{% endblock %}

templates/services.html
{% extends 'base.html' %}
{% comment %} {% load static %} {% endcomment %}
<!DOCTYPE html>
<html lang = "en">
<head>
    <meta charset = "UTF-8">
    <meta name ="viewport" content ="width=device-width , initial-scale=1.0">
    {% block title %}Services{% endblock title %}
     
   

 
    
</head>

{% block body %}
<form class="d-flex align-items-end bg-light mb-3" action ="/search" method="GET">
 <input class="form-control " type="search" name="keyword" placeholder="Search Services here...." aria-label="Search">
<button type="submit" class="btn btn-primary">
    <i class="fa fa-search"></i>
  </button>
</form>
<main>


 
<div class ="container-fluid mt-2">
    <div class="row">
  
        <div class="col-lg-3 mx-auto">
        <h5> Select Service category</h5>
   
            <ul class="list-group">
                <li class="list-group-item"><a href="{% url 'service_app:services' %}">All</a>
                </li>
                {%for category in categories%}
                
                <li class="list-group-item">
                    <a href = "{{category.get_absolute_url}}">{{category.name}}</a>
                </li>
                {% endfor %}
            </ul>
        </div>
        {% if categorie %}{% else %}{% endif %}
        <div class="col-lg-9 mx-auto" >
            <div class ="row mx-auto">
             {% for s in service %}
           
                <div class="card mx-auto mb-3 shadow-sm" style="width:18rem;">
                    <img src="/media/{{s.image}}" class=" card-img-top" alt="/"style="height: 250px;width: 285px;">            
                        <div class="card-body"> 
                            <p class="card-title">{{s.name}}</p>
                            <p class="card-text"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16"><path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/><path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/></svg>&nbsp;{{s.Duration}}</p>
                            <p class="card-text"><i class="fa fa-inr"></i>&nbsp;{{s.price}}</p>
                           
                                <div class="btn-group">
                                    <a href="addtocart/{{s.id}}" class="btn btn-primary cart">Add to Cart</a> &nbsp;&nbsp;&nbsp;
                                    <a href="showservice/{{s.id}}"><button  class="btn btn-primary cart" id="qv{{s.id}}" >QuickView</button></a>
                                </div>
                            
                        </div>
                </div>
              
                {% endfor %}
          </div>
    </div>
    </div>
</div>

</main> 


 
 {% block js %}
{% endblock js %} 
{% endblock body%}


</html>

templates/showservice.html
{% extends 'base.html' %}

{% block title %}{{service.name}}{% endblock title %}

{% block body %}
<div class ="container my-4">
  <div class="row">
    <div class ="col-md-4">
      <div class="row">
        <img src="/media/{{service.image}}" width="250px" height="300px">
     </div>
  </div>
<div class="col-md-8">
      <h5>{{service.name}}</h5>
       <p><i class="fa fa-inr"></i>&nbsp;<b>{{service.price}}</b></p>
        <p> {{service.Warranty}}</p>
        <p><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-clock" viewBox="0 0 16 16"><path d="M8 3.5a.5.5 0 0 0-1 0V9a.5.5 0 0 0 .252.434l3.5 2a.5.5 0 0 0 .496-.868L8 8.71V3.5z"/><path d="M8 16A8 8 0 1 0 8 0a8 8 0 0 0 0 16zm7-8A7 7 0 1 1 1 8a7 7 0 0 1 14 0z"/></svg>
         {{service.Duration}}</p>
      <p>{{service.what_included}}</p>
      
  </div>
</div>
</div>



{% endblock body %} 